name: innesto
type: typo3
docroot: .Build/public
php_version: "8.4"
webserver_type: nginx-fpm
database:
  type: mariadb
  version: "10.11"
use_dns_when_possible: true
web_environment:
  - TYPO3_CONTEXT=Development
